### ISSUE TITLE
V22.0 General Test Cases

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#3007]
## Fork resource usage

- [x] See Fork resource usage test cases #3041 for full testing details

## Experimental Pruning

- [x] See Experimental Pruning Test Cases #3008 for full testing details.

## Vote timestamps

- [x] See Vote timestamps Test Cases #3009 for full testing details.

## Load testing
The following load tests are useful to run with each DB if time and resources permit, but will be required with the final DB before transitioning to the first RC build.

- [ ] LT1: Maximum throughput multi-account test. Success measured in terms of expected regression from previous values, weighted against current network differences.
- [ ] LT2: High speed single account test. Success measured in terms of wasted resources (e.g., starting an election for the frontier repeatedly, possibly multiple times as the test runs due to the frontier changing quickly).
- [ ] LT3: High speed single account + opening + sending from multiple accounts created by the single account. Success measured in terms of wasted resources (e.g., starting an election for each account's frontier repeatedly).
- [ ] LT4: High throughput horizontal dependency test, i.e., send -> open -> send -> open -> ... to new accounts on every send.
- [ ] LT5: To help mimic more real life scenarios, running these tests with normal users attempting to push their blocks, and updating their difficulty when necessary, is encouraged. Success for these normal users can be measured in how fast their blocks confirm when given unlimited work generation.

### Added in DB15

**Sighup reload bandwidth params #3257**

- [x] Remove existing `node.bandwidth_limit` value and send `kill -SIGHUP [process #]` to node running on Linux and validate configuration change was picked up

### Added in DB10

**Add --rpcconfig option and fix wallet config bug #3069**

- [ ] Pass in options from `config-rpc.toml` using `--rpcconfig` flag and verify they function properly

**Add confirmed_height in account_info RPC to be consistent #3039**

- [x] Test for `confirmed_height` return with new `include_confirmed` flag and `confirmation_height` without flag

**Fix online reps live votes update #3084**

- [x] During heavy traffic tests, validate online weight remains steady without drops and spikes seen in previous versions

**Migrate LMDB database to RocksDB with new CLI command #2979**

- [x] Once ledger gets to at least 1MM blocks, preferably with a variety of different types of sends, attempt the upgrade to RocksDB - note results in comments along with hardware specs

**Renew UPNP port lease #3035**

- [ ] For nodes previously having dropped or dangling peers due to UPnP issues, evaluate connections are behaving as expected

**Pending RPC to sort by absolute amounts when returning a subset #3060**

- [ ] Verify results are a subset from the full set of pending

**Add option to include votes in confirmation websocket #3016**

- [x] Setup subscription to confirmations with optional `include_election_info_with_votes` and validate vote data in notifications (likely best under light load)

### Added in DB9

**Remove telemetry signature partitions #3014**

- [x] Modify a node to send out some extra "unknown_data" (simulate a newer telemetry version communicating) in the `telemetry_ack` message and make sure other peers don't blacklist us and can still process the telemetry message
- [x] Vice versa, make sure we can understand the old messages

**Add pruned node to maker #3013**

- [x] Verify pruned nodes are publishing `maker` value in telemetry of `1` when pruning enabled, `0` when not pruning

### Added in DB8

- [x] **Rollback messages are no longer included in logs by default #2998** - enable via `ledger_rollback` option under `node.logging` section

**Comment by bdsvc-github** [comment]
Deployment starting to ephemeral!

**Comment by bdsvc-github** [comment]
Deployed to ephemeral!

**Comment by zhyatt** [comment]
With DB8 there were some LT1 tests done to help capture data for #3009 and there wasn't any obvious regression issues given the network setup (25-30 nodes, 10 of which were pruned low spec ones). Saturation levels around 1200BPS or so range. Leaving LT1 open for testing in future DBs.

**Comment by wezrule** [comment]
I manually modified my telemetry data on a node to send more data than other peers would understand and didn't appear to get banned by any (peer connections were maintained). Confirmed on a separate node than the telemetry it received from this modified node too is parsed correctly.

**Comment by zhyatt** [comment]
Great thanks @wezrule - marked telemetry related test cases as finished, including the maker piece which was separately verified.
